### ISSUE TITLE
x-internal does not filter the referenced properties from object

### ISSUE THREAD

**Issue by djoshi0** [Mermade/openapi-filter#169]
User.yaml
```
type: object
properties:
  name: 
    type: string
  userSecret:
    x-internal: true
    $ref: 'UserSecretInfo.yaml'
```

The user secret is not removed from target yaml after applying the filter
