### ISSUE TITLE
Single/Double quotes removed from example

### ISSUE THREAD

**Issue by nelsoncc** [Mermade/openapi-filter#31]
I'm trying to use an example for a property, whose type is date-time:
e.g.: example: '20:30'

But it's removing the single/double quotes in the output. The same happens with date format.

input:
```yml
...
components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
        shipDateTime:
          type: string
          format: date-time
          example: '20:30'
        shipDate:
          type: string
          format: date
          example: '2020-05-05'
...
```

output:
```yml
...
components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
        shipDateTime:
          type: string
          format: date-time
          example: 20:30
        shipDate:
          type: string
          format: date
          example: 2020-05-05
...
```

expected:
```yml
...
components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
        shipDateTime:
          type: string
          format: date-time
          example: '20:30'
        shipDate:
          type: string
          format: date
          example: '2020-05-05'
...
```
Thanks in advance.
